name: 'CORE-Refactor'
description: 'Tool to refactor code and suggest suitable go packages in place of user code to make source code concise and efficient.'

inputs:
  GOOGLE_API_KEY:
    description: 'Google API key'
    required: true
  ANTHROPIC_API_KEY:
    description: 'Anthropic API key'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB API key'
    required: true
  REPO_NAME:
    description: 'Repo name'
    required: true
  #REPO_OWNER:
   # description: 'repo owner'
    #required: true
  #PR_NUMBER:
   # description: 'pr number'
   # required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
      shell: bash
    - name: Install dependencies
      run: |
        python3 -m pip install ipykernel
        python3 -m ipykernel install --user
        pip install -q llama-index-llms-gemini
        pip install -q llama-index google-generativeai
        pip install -q llama-index-embeddings-gemini
        pip install -q chromadb
        pip install -q llama-index-vector-stores-chroma
        pip install -q llama-index-llms-anthropic
        pip install -q github
        pip install -q PyGitHub
        pip install -q nbconvert
        pip install -q tree-sitter-go
        pip install -q tree-sitter
        pip install -q cython
        pip install -q pysqlite3
      shell: bash
    - name: Run Jupyter Notebook
      env:
        GOOGLE_API_KEY: ${{ inputs.GOOGLE_API_KEY}}
        ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPO_NAME: ${{ inputs.github.event.repository.name }}
        #REPO_OWNER: ${{ inputs.github.event.repository.owner }}
        #PR_NUMBER: ${{ inputs.github.event.number }}
        
      run: python ${{ github.workspace }}/src_core.py
      shell: bash
