name: CORE-Refactor
description: Tool to refactor code and suggest suitable go packages in place of user code to make source code concise and efficient.

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-notebook:
    runs-on:  ubuntu-latest

    
   inputs:
    GOOGLE_API_KEY:
      description: 'GOOGLE API Key'
      required: true
    GITHUB_TOKEN:
      description: 'Github token'
      required: true
    ANTHROPIC_API_KEY:
      description: 'ANTHROPIC API Key'
      required: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python3 -m pip install ipykernel
          python3 -m ipykernel install --user
          pip install -q llama-index-llms-gemini
          pip install -q llama-index google-generativeai
          pip install -q llama-index-embeddings-gemini
          pip install -q chromadb
          pip install -q llama-index-vector-stores-chroma
          pip install -q llama-index-llms-anthropic
          pip install -q PyGithub
          pip install -q github
          pip install -q nbconvert
          pip install -q cython
        
          
      - name: Set environment variables
        run: |
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Run Jupyter Notebook
        run: python src_core.py
