name: Run Python

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-notebook:
    runs-on:  ubuntu-20.04 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python3 -m pip install ipykernel
          python3 -m ipykernel install --user
          pip install -q llama-index-llms-gemini
          pip install -q llama-index google-generativeai
          pip install -q llama-index-embeddings-gemini
          pip install -q chromadb
          pip install -q llama-index-vector-stores-chroma
          pip install -q llama-index-llms-anthropic
          pip install -q PyGithub
          pip install -q github
          pip install -q nbconvert
          pip install -q cython
          pip install -q aiohttp==3.9.5
         
          
      - name: Set environment variables
        run: |
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Run Jupyter Notebook
        run: python src_core.py
